name: Pyright

on: [push]

jobs:
  pyright:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          cache: 'poetry'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          echo "$(poetry env info --path)/bin" >> $GITHUB_PATH
          pip install pyright
      - uses: jakebailey/pyright-action@v2
        with:
          working-directory: "./src"
